[tool.poetry]
name = "ape_ens"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
eth-ape = "^0.6.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
